### ISSUE TITLE
Monarch UI not working on macos with Flutter 3.24.3

### ISSUE THREAD

**Issue by zawadZwd** [Dropsource/monarch#150]
Hey, i've created a basic flutter project, on the version 3.24.3. After run the command *monarch run*, i have the following error:

```bash
Enabling Flutter for desktop

Downloading the Monarch UI for this project's flutter version...

We could not find a compatible Monarch UI for this version of Monarch and Flutter.
You could try switching Flutter versions. Or, create a GitHub issue in the Monarch repo 
and let us know which Flutter version your project is using: 
https://github.com/Dropsource/monarch/issues
```

The flutter doctor response:

```bash
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)            
[✓] Network resources
```

The project structure looks like this:

<img width="258" alt="image" src="https://github.com/user-attachments/assets/18a16312-3045-4e87-aacd-a9b2a996cbb9">

and the pubspec.yaml like this:

```yaml
name: counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  monarch: ^3.8.1

flutter:
  uses-material-design: true

```

Did i miss something? I've followed by [https://monarchapp.io/docs/install](url), and I've installed monarch_macos_2.2.7.zip. 
I suspect the newest macos version but it is just a shot.
