### ISSUE TITLE
Support classification of layers

### ISSUE THREAD

**Issue by seito2** [Dropsource/monarch#24]
I want to use like `/atoms/**/*.dart` for atomic design pattern.
Is this already supported?

If no, is it able to support for this?
thanks.

**Comment by fertrig** [comment]
Monarch will look for stories in files that end in `*_stories.dart`. Those files could be in nested sub-directories. 

You can also tell Monarch which directories to search on by editing the file build.yaml:
```
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - stories/**
      - atoms/**
```

I'm not sure if this answers your question though. Please let me know.
