### ISSUE TITLE
Broken mockito generation after monarch init

### ISSUE THREAD

**Issue by cerealexx** [Dropsource/monarch#41]
Monarch init removes all my .mocks files and breaks code generation for them afterwards.
Any ideas on how to fix this?

**Comment by fertrig** [comment]
Please make sure to add the directory of your .mocks files in your build.yaml. If you are using mockito, then the directory is usually `test`. 

Here is an example build.yaml which supports the monarch directories and the `test` directory:
```yaml
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - stories/**
      - test/**
```

The code generation will now include the `test` directory, so after you run `flutter pub run build_runner build` all the .mocks files in the test directory should show up.
